name: Google Artifact Registry Login

inputs:
  GCP_WORKLOAD_IDENTITY_PROVIDER:
    required: true
  GCP_SERVICE_ACCOUNT_EMAIL:
    required: true

description: Authenticate to Google Cloud and login to Google Artifact Registry.

runs:
  using: composite
  steps:
    - id: auth
      name: "Authenticate to Google Cloud"
      uses: google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033
      with:
        create_credentials_file: false
        token_format: "access_token"
        workload_identity_provider: ${{ inputs.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ inputs.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Login to Google Artifact Registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      with:
        registry: us-docker.pkg.dev # use multi-region GAR
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
