name: Setup docker buildx

runs:
  using: composite
  steps:
    - name: setup docker context for buildx
      id: buildx-context
      shell: bash
      run: docker context create builders
    - name: setup docker buildx
      uses: docker/setup-buildx-action@ecf95283f03858871ff00b787d79c419715afc34
      with:
        endpoint: builders
        version: v0.8.2
