type: all_in_one
processor_config:
  stream_subscriber_config:
    indexer_grpc_data_service_address: https://grpc.testnet.aptoslabs.com:443
    auth_token: replace_me
  dispatcher_config: {}
  common_storage_config:
    initial_starting_version: 709391160
  processor_config:
    canvas_contract_address: "0xbb71ff0f8e8780c0e8a53cf003116ab96dc877394cf2cf4d54e71c1667373146"
pixel_storage_config:
  storage_directory: /tmp/canvases
metadata_storage_config:
  connection_string: "postgres://dport:@localhost:5432/canvas"
api_config: {}
local_flusher_config:
  flush_dir: /tmp/flushed
