type: all_in_one
processor_config:
  stream_subscriber_config:
    indexer_grpc_data_service_address: https://grpc.mainnet.aptoslabs.com:443
    auth_token: replace_me
  dispatcher_config: {}
  common_storage_config:
    initial_starting_version: 298334701
  processor_config:
    canvas_contract_address: "0x0bf59936bba20c6cfc14f2465ec7f7645b43c935c539d9de187fe2a7c859062e"
    disable_metadata_processing: true
pixel_storage_config:
  storage_directory: /tmp/canvases
metadata_storage_config:
  connection_string: "postgres://dport:@localhost:5432/canvas"
api_config: {}
local_flusher_config:
  flush_dir: /tmp/flushed
