type: all_in_one
processor_config:
  stream_subscriber_config:
    indexer_grpc_data_service_address: https://grpc.testnet.aptoslabs.com:443
    auth_token: dummy_token
  dispatcher_config: {}
  common_storage_config:
    initial_starting_version: 701566480
  processor_config:
    canvas_contract_address: "0xb764b4baa21a53b7af4ea6688674d385e3255871021de12ddd6be5e004e92fec"
pixel_storage_config:
  storage_directory: /tmp/canvases
metadata_storage_config:
  connection_string: "postgres://dport:@localhost:5432/canvas"
api_config: {}
local_flusher_config:
  flush_dir: /tmp/flushed
