type: all_in_one
processor_config:
  stream_subscriber_config:
    indexer_grpc_data_service_address: https://grpc.testnet.aptoslabs.com:443
    auth_token: replace_me
  dispatcher_config: {}
  common_storage_config:
    initial_starting_version: 713919450
  processor_config:
    canvas_contract_address: "0x6b8169be66d9579ba9ad1192708edcf52de713d3513a431df6cb045f425d3d91"
    disable_metadata_processing: true
pixel_storage_config:
  storage_directory: /tmp/canvases
metadata_storage_config:
  connection_string: "postgres://dport:@localhost:5432/canvas"
api_config: {}
local_flusher_config:
  flush_dir: /tmp/flushed
